import React, { useEffect, useRef, useState } from 'react';
import { useAgenticScrollGrade } from './useAgenticScrollGrade';
import { AgenticHazeLayer } from './AgenticHazeLayer';
import { PollutionScrollField } from './PollutionScrollField';
import { AgenticFogWipe } from './AgenticFogWipe';
import { AgenticBeat } from './AgenticBeat';
import { HowItFeelsToLiveHere } from './HowItFeelsToLiveHere';
import { DiurnalRibbon } from './DiurnalRibbon';
import { MonthlyParticleBars } from './MonthlyParticleBars';
import { CitySimulation } from './CitySimulation';
import { RecoveryClock } from './RecoveryClock';
import { SmallThingsThatHold } from './SmallThingsThatHold';
import { PersonalizedClosing } from './PersonalizedClosing';

// Beats below scroll as normal page content (no nested scroll region - a fixed-height,
// overflow:auto box here used to trap the mouse wheel until the visitor scrolled through every
// slide, which is exactly the "can't get out of this section" complaint this replaces). A
// drifting fog bank (plus a wind whoosh) still fires once per beat, now triggered by an
// IntersectionObserver watching a thin band near the viewport centre instead of reading a
// container's scrollTop.
function useAgenticSlideDeck(
  slideRefs: React.MutableRefObject<Array<HTMLDivElement | null>>,
  prefersReducedMotion: boolean
) {
  const [wipeKey, setWipeKey] = useState<number | null>(null);
  const activeIndexRef = useRef<number | null>(null);
  const wipeCounterRef = useRef(0);

  useEffect(() => {
    if (prefersReducedMotion) return undefined;
    const elements = slideRefs.current.filter((el): el is HTMLDivElement => Boolean(el));
    if (!elements.length) return undefined;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (!entry.isIntersecting) return;
          const index = elements.indexOf(entry.target as HTMLDivElement);
          if (index === -1 || index === activeIndexRef.current) return;
          activeIndexRef.current = index;
          wipeCounterRef.current += 1;
          setWipeKey(wipeCounterRef.current);
        });
      },
      { rootMargin: '-45% 0px -45% 0px', threshold: 0 }
    );

    elements.forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, [slideRefs, prefersReducedMotion]);

  return wipeKey;
}

const SLIDE_COUNT = 6;

export const AgenticAiSection: React.FC = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  const slideRefs = useRef<Array<HTMLDivElement | null>>(new Array(SLIDE_COUNT).fill(null));
  const { tint, haze, prefersReducedMotion } = useAgenticScrollGrade(sectionRef);
  const wipeKey = useAgenticSlideDeck(slideRefs, prefersReducedMotion);

  const setSlideRef = (index: number) => (el: HTMLDivElement | null) => {
    slideRefs.current[index] = el;
  };

  return (
    <div ref={sectionRef} className="relative w-full overflow-hidden bg-transparent">
      <AgenticHazeLayer tint={tint} haze={haze} prefersReducedMotion={prefersReducedMotion} />
      <PollutionScrollField severity={haze} />
      <AgenticFogWipe triggerKey={wipeKey} />

      <div className="relative z-[1] mx-auto max-w-[510rem] px-6 py-4 text-center md:px-10">
        <p className="truncate text-sm" style={{ color: 'var(--ss-muted)' }}>
          <span className="font-bold uppercase tracking-[0.25em]" style={{ color: 'var(--ss-accent)' }}>
            Agentic AI
          </span>
          <span className="mx-2">·</span>
          <span className="font-bold" style={{ color: 'var(--ss-text)' }}>
            A machine that writes back
          </span>
          <span className="mx-2">·</span>
          Generated by Ollama, running locally, as you scroll and click.
        </p>
      </div>

      <div className="relative z-[1]">
        <div ref={setSlideRef(0)} className="agentic-slide flex min-h-[42.5vh] flex-col justify-center">
          <AgenticBeat eyebrow="In plain terms" title="How It Feels To Live Here" accent="#f87171">
            <HowItFeelsToLiveHere />
            <DiurnalRibbon />
          </AgenticBeat>
        </div>

        <div ref={setSlideRef(1)} className="agentic-slide flex min-h-[42.5vh] flex-col justify-center">
          <AgenticBeat eyebrow="The shape of a year" title="Twelve Months, in Particles" accent="#38bdf8">
            <MonthlyParticleBars />
          </AgenticBeat>
        </div>

        <div ref={setSlideRef(2)} className="agentic-slide flex min-h-[42.5vh] flex-col justify-center">
          <AgenticBeat eyebrow="Play it forward" title="Simulate The Next Years" accent="#f59e0b">
            <CitySimulation />
          </AgenticBeat>
        </div>

        <div ref={setSlideRef(3)} className="agentic-slide flex min-h-[42.5vh] flex-col justify-center">
          <AgenticBeat eyebrow="The reversal" title="One Recovery, at Every Scale" accent="#16a34a">
            <RecoveryClock />
          </AgenticBeat>
        </div>

        <div ref={setSlideRef(4)} className="agentic-slide flex min-h-[42.5vh] flex-col justify-center">
          <AgenticBeat eyebrow="Reminders" title="Quiet Truths About the Air" accent="#38bdf8">
            <p className="mx-auto -mt-3 mb-6 max-w-xl text-center text-sm" style={{ color: 'var(--ss-muted)' }}>
              Six small, true things about air and the people who breathe it - tap a card to read one more thought.
            </p>
            <SmallThingsThatHold />
          </AgenticBeat>
        </div>

        <div ref={setSlideRef(5)} className="agentic-slide flex min-h-[42.5vh] flex-col justify-center">
          <AgenticBeat
            eyebrow="Finally"
            title="Make It About You"
            accent="#7ab8e6"
            className="relative z-[1] mx-auto w-full max-w-[510rem] px-6 pb-16 pt-20 text-center md:px-10"
          >
            <p className="mx-auto -mt-3 mb-6 max-w-xl text-center text-sm" style={{ color: 'var(--ss-muted)' }}>
              Pick your city, who you're asking for, and what's on your mind - we'll write something just for that.
            </p>
            <PersonalizedClosing />
          </AgenticBeat>
        </div>
      </div>
    </div>
  );
};
