import React from 'react';

type Props = {
  className?: string;
  label?: string;
};

// Small attribution line for the two Ollama-driven story tabs (AI Generated, Agentic AI). One
// per tab, not per widget - individual visualizations already carry their own smaller
// "Ollama generated" tag (see AgenticCaption.tsx) where it matters at that scale.
export const GeneratedByOllama: React.FC<Props> = ({ className, label = 'Generated by Ollama, running locally' }) => (
  <p
    className={className ?? 'text-center text-xs font-semibold uppercase tracking-[0.18em]'}
    style={{ color: 'var(--ss-muted, #8b8780)' }}
  >
    {label}
  </p>
);
